encoding: utf-8
title: TMaize'Blog

# seo
description: TMaize'Blog
keywords: TMaize,Blog,TMaize'Blog
author: TMaize

baseurl: ""
home: /
categoriesurl: /pages/categories
searchurl: /pages/search
linksurl: /pages/links
chaturl: /pages/chat
abouturl: /pages/about

cssurl: /static/css
jsurl: /static/js

permalink: /posts/:title.html