encoding: utf-8
title: TMaize'Blog

# seo
description: TMaize'Blog
keywords: TMaize,Blog,TMaize'Blog
author: TMaize

baseurl: ""
domainurl: "http://blog.tmaize.net"

home: /
categoriesurl: /pages/categories
searchurl: /pages/search
linksurl: /pages/links
chaturl: /pages/chat
abouturl: /pages/about

cssurl: /static/css
jsurl: /static/js

permalink: /posts/:year/:month/:day/:title.html

beian: "皖ICP备16016174号"

coderay:
  coderay_tab_width: 4